name: Release Drafter
description: 'Release drafter action'

inputs:
  token:
    description: 'github access token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: ls $GITHUB_ACTION_PATH && echo "CONFIG_FILE=$GITHUB_ACTION_PATH/config/release-drafter.yml" >> $GITHUB_ENV
      shell: bash
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: run Release Drafter
      uses: release-drafter/release-drafter@v5
      # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      # with:
        # config-name: ${{ env.CONFIG_FILE }}
      #   disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
