name: Release Drafter
description: 'Release drafter action'

inputs:
  token:
    description: 'github access token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: pwd && ls -a && cp ${{ github.action_path }}/config/release-drafter.yml .github/release-drafter.yml 
      shell: bash
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: run Release Drafter
      uses: release-drafter/release-drafter@v5
      # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      with:
        config-name: release-drafter.yml
      #   disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
