name: Release Drafter
description: 'Release drafter action'

inputs:
  token:
    description: 'github access token'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - uses: release-drafter/release-drafter@v5
      # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      with:
        config-name: config/release-drafter.yml
      #   disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
