name: Release Drafter
description: 'Release drafter action'

inputs:
  token:
    description: 'github access token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: mkdir -p .github && cp config/release-drafter.yml .github/release-drafter.yml 
      shell: bash
      working-directory: ${{ github.action_path }}
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: run Release Drafter
      uses: release-drafter/release-drafter@v5
      # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      with:
        config-name: release-drafter.yml
      #   disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
